### ISSUE TITLE
[readme] create codeql badge

### ISSUE THREAD

**Issue by akshayitzme** [akshayitzme/zuno#14]
### desc: repo is configured with codeql code checking. so we can include a codeql code check branch

target file: `README.md`

### Hint 
- add the following code in 3rd line of the readme
```md
![GitHub Workflow Status](https://img.shields.io/github/workflow/status/akshayitzme/zuno/CodeQL?style=for-the-badge)
```

**Comment by shania-maria** [comment]
I would like to work on this issue.
