### ISSUE TITLE
[UI]  Add Rounded Style to Username Input Button

### ISSUE THREAD

**Issue by akshayitzme** [akshayitzme/zuno#2]
### Task: Apply border-radius to user input tag to improve its design.

Target File: `components/SearchForm.jsx`

Hints: 

- Current Code
  `<input name="username" onChange={formik.handleChange} value={formik.values.username} className="h-12 p-2 text-black" type="search" placehoder="github username" />
`

- Change Into

 `<input name="username" onChange={formik.handleChange} value={formik.values.username} className="h-12 p-2 text-black rounded" type="search" placehoder="github username" />`

**Comment by shania-maria** [comment]
I would like to contribute to this project.
