### ISSUE TITLE
[Ui] Style Submit Button

### ISSUE THREAD

**Issue by akshayitzme** [akshayitzme/zuno#9]
### Target File: `components/SearchForm.jsx`
- line 22

### Hints
- remove `bg-white` class we no longer need it
- add `bg-2` class to the button to match the color with the theme
- change the button height.. i think giving `h-12` class will be fine 
- give a padding of 2 `p-2`
- add `rounded` class 
- always welcome for new ideas

final code may look like this:
```javascript 
<button className="h-12 bg-2 p-2 rounded" type="submit">Submit</button> 
```

**Comment by Yash-271120** [comment]
@akshayitzme Plz assign this issue to me, I would like to work on this issue. :)
